# Generated by Django 3.1.3 on 2020-11-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200925_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexables',
            name='indexable_date',
        ),
        migrations.AddField(
            model_name='indexables',
            name='indexable_date_range_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexables',
            name='indexable_date_range_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
