# Generated by Django 3.1.3 on 2021-01-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20201120_1253'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indexables',
            name='search_inde_origina_7999e9_idx',
        ),
    ]
