# Generated by Django 3.1.6 on 2021-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210122_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='iiifresource',
            name='first_canvas_id',
            field=models.URLField(blank=True, null=True, verbose_name='First canvas IIIF id'),
        ),
        migrations.AddField(
            model_name='iiifresource',
            name='first_canvas_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
