# Generated by Django 3.1.6 on 2021-03-08 11:46

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iiif_search', '0005_auto_20210216_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=512, populate_from='id'),
        ),
        migrations.AlterField(
            model_name='iiifresource',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=512, populate_from='madoc_id'),
        ),
    ]
