# Generated by Django 3.1.6 on 2021-03-08 17:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210308_1146'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indexables',
            index=django.contrib.postgres.indexes.HashIndex(fields=['indexable'], name='search_inde_indexab_3d4d48_hash'),
        ),
    ]
