# Generated by Django 3.1.6 on 2021-04-23 14:56

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif_search', '0008_auto_20210308_1743'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indexables',
            name='iiif_search_inde_search__09e477_gin',
        ),
        migrations.RemoveIndex(
            model_name='indexables',
            name='iiif_search_inde_content_2b8043_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexables',
            name='iiif_search_inde_type_8a963a_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexables',
            name='iiif_search_inde_subtype_c91e89_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexables',
            name='iiif_search_inde_languag_e4a69b_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexables',
            name='iiif_search_inde_indexab_3d4d48_hash',
        ),
        migrations.RemoveIndex(
            model_name='indexables',
            name='iiif_search_inde_type_bdb46f_idx',
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='iiif_search_search__3b14c2_gin'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['content_id'], name='iiif_search_content_3fc897_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['language_iso639_2', 'language_iso639_1', 'language_display'], name='iiif_search_languag_4f966c_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['type'], name='iiif_search_type_922f99_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['subtype'], name='iiif_search_subtype_df84cc_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['type', 'subtype'], name='iiif_search_type_993c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=django.contrib.postgres.indexes.HashIndex(fields=['indexable'], name='iiif_search_indexab_83e330_hash'),
        ),
    ]
