# Generated by Django 3.1.3 on 2021-09-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20210308_1743'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['type'], name='search_iiif_type_26fb56_idx'),
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['madoc_id'], name='search_iiif_madoc_i_6b75fc_idx'),
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['id'], name='search_iiif_id_b3f508_idx'),
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['label'], name='search_iiif_label_a82425_idx'),
        ),
    ]
