# Generated by Django 3.1.6 on 2021-11-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif_search', '0009_auto_20210423_1456'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['type'], name='iiif_search_type_b0e083_idx'),
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['madoc_id'], name='iiif_search_madoc_i_4f31ae_idx'),
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['id'], name='iiif_search_id_c181f8_idx'),
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['label'], name='iiif_search_label_93a806_idx'),
        ),
    ]
