# Generated by Django 4.0 on 2022-02-16 11:10

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20210924_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iiifresource',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='ispartof', to='search.IIIFResource'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['resource_id'], name='search_inde_resourc_249a71_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('type'), name='uppercase_type'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('subtype'), name='uppercase_subtype'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('type'), django.db.models.functions.text.Upper('subtype'), name='uppercase_type_subtype'),
        ),
    ]
