# Generated by Django 4.0 on 2021-12-15 17:09

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('iiif_search', '0010_auto_20211105_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iiifresource',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='ispartof', to='iiif_search.IIIFResource'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(fields=['resource_id'], name='iiif_search_resourc_42b2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('type'), name='uppercase_type'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('subtype'), name='uppercase_subtype'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('type'), django.db.models.functions.text.Upper('subtype'), name='uppercase_type_subtype'),
        ),
        migrations.AddIndex(
            model_name='indexables',
            index=models.Index(django.db.models.functions.text.Upper('type'), django.db.models.functions.text.Upper('subtype'), django.db.models.functions.text.Upper('indexable'), name='uppercase_indexables'),
        ),
    ]
