# Generated by Django 4.0 on 2022-01-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_alter_iiifresource_items_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indexables',
            name='uppercase_indexables',
        ),
    ]
